Adding setup-avahi-discovery role
SatelliteQE/ansible-satellite6 pull request #18
Opened 2018-08-01 14:30 UTC by chbrown13

Ansible role for the automation-tools setup_avahi_discovery task

2018-08-01 17:45 UTC, JacobCallahan commented on roles/avahi/tasks/restart_avahi.yml
> +    state: restarted
+1

2018-08-01 23:45 UTC, ehelms commented on roles/avahi/tasks/add_mdns_service.yml
> +
Can remove

2018-08-01 23:46 UTC, ehelms approved these changes

2018-08-02 04:18 UTC, kbidarkar commented
@chbrown13, Can you please add this to the excel sheet, which was shared.

2018-08-02 04:28 UTC, kbidarkar requested changes
Ansible stuff appears to be fine, but request to please squash these commits.

I would still say the same even though Github has the option to squash the commits and merge them.

As it would probably pick the commit message related to docker roles instead of setup-avahi roles.

2018-08-02 18:06 UTC, pgagne commented
Why do we need Avah againi?

2018-08-02 19:06 UTC, kbidarkar commented
when I saw this PR, I thought why we need Avahi with SatLab, but on thinking again realized,

Probably we want to have this repo more generic and not keeping SatLab focused and hence feel Avahi is ok to have. 
If we go down the road of having only those stuff which would be required with SatLab, we would end up not being able to share the repo with anyone else outside our team, who do not have access to SatLab. Which we may not want to do.

Though, currently, I would not include avahi roles into the playbooks created already, but probably have another playbook.

2018-08-03 04:11 UTC, kbidarkar commented
Thanks, @chbrown13   for squashing the commits.

2018-08-11 14:50 UTC, kbidarkar approved these changes

2018-08-11 14:50 UTC, merged

2018-08-29 11:30 UTC, lpramuk commented on roles/avahi/tasks/restart_avahi.yml
> +    state: restarted
-1